baseURL = 'https://amaro0.xyz/'
languageCode = 'en-us'
title = ''
theme = 'hugo-bearblog'
enableRobotsTXT = true

[permalinks]
blog = "/:slug/"
tags = "/blog/:slug"

[params]
#global comments enable
comments = true